packages:
  - packages/*

catalogs:
  build:
    '@vueuse/core': ^13.1.0
    vue: ^3.5.13

  dev:
    '@antfu/ni': ^24.3.0
    '@unocss/reset': ^66.1.0-beta.5
    bumpp: ^10.1.0
    pnpm: ^10.10.0
    typescript: ^5.6.3
    unocss: ^66.1.0-beta.5
    unplugin-vue-components: ^28.5.0
    vue-tsc: ^2.2.10

  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/material-symbols': ^1.2.20

  lint:
    '@antfu/eslint-config': ^4.13.0
    '@unocss/eslint-plugin': ^66.1.0-beta.5
    eslint: ^9.26.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.13.0

  types:
    '@types/chrome': ^0.0.321

  wxt:
    '@wxt-dev/module-vue': ^1.0.2
    wxt: ^0.20.6
